- hosts: windows_web

  tasks:
    - name: add user operator
      win_user:
        name: studentX
        password: '0p$4@ll'
        groups:
         - Remote Desktop Users

    - name: Add or update the registry and leave your mark
      win_regedit:
        key: HKCU:\Software\Ansible
        name: studentX
        data: foo

