- hosts: lab_servers

  tasks:
    - name: add user operator
      win_user:
        name: student1
        password: 0p$4@ll

    - name: Add or update the registry and leave your mark
      win_regedit:
        key: HKCU:\Software\Ansible
        name: student1
        data: foo

    - name: Install Web Server
      win_feature:
        name: Web-Server
        state: present

    - name: Create web directory
      win_file:
        path: c:\www\student1
        state: directory

    - name: Create web index
      win_lineinfile:
        path: C:\www\student1\index.html
        create: yes
        line: "Hello World from {{ ansible_hostname }} at {{ ansible_ssh_host }}"

    - name: Build web site
      win_iis_website:
        name: "Web site"
        hostname: "student1.{{ ansible_ssh_host }}.xip.io"
        physical_path: c:\www\student1
