- hosts: windows_web
  vars:
    student_username: studentX

  tasks:
    - name: Install Web Server
      win_feature:
        name: Web-Server
        state: present

    - name: Create web directory
      win_file:
        path: "c:\\www\\{{ student_username }}"
        state: directory

    - name: Create web index
      win_lineinfile:
        path: "C:\\www\\{{ student_username }}\\index.html"
        create: yes
        line: "Hello World from {{ ansible_hostname }} at {{ ansible_ssh_host }} by {{ student_username }}"

    - name: Build web site
      win_iis_website:
        name: "{{ student_username }} Web site"
        hostname: "{{ student_username }}.{{ ansible_ssh_host }}.xip.io"
        physical_path: "c:\\www\\{{ student_username }}"
